services:
  laravel:
    build: .
    container_name: laravel
    environment:
      PHP_OPCACHE_ENABLE: 1
      PRODUCTION: 0
    ports:
      - 8081:80
    volumes:
      - .:/opt/laravel
      - vendor-data:/opt/laravel/vendor
      - storage-data:/opt/laravel/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://laravel/"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  vendor-data:
  storage-data:
  dbdata:
